// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spectacole_Teatru_Project.Data;

#nullable disable

namespace Spectacole_Teatru_Project.Migrations
{
    [DbContext(typeof(Spectacole_Teatru_ProjectContext))]
    [Migration("20220125220803_CategorieSpectacol")]
    partial class CategorieSpectacol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CategorieSpectacol", b =>
                {
                    b.Property<int>("CategoriiSpectacolID")
                        .HasColumnType("int");

                    b.Property<int>("CategoriiSpectacolID1")
                        .HasColumnType("int");

                    b.HasKey("CategoriiSpectacolID", "CategoriiSpectacolID1");

                    b.HasIndex("CategoriiSpectacolID1");

                    b.ToTable("CategorieSpectacol");
                });

            modelBuilder.Entity("Spectacole_Teatru_Project.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume_Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Spectacole_Teatru_Project.Models.Regizor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume_Regizor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Regizor");
                });

            modelBuilder.Entity("Spectacole_Teatru_Project.Models.Spectacol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume_Piesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("RegizorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SpectacolDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("RegizorID");

                    b.ToTable("Spectacol");
                });

            modelBuilder.Entity("CategorieSpectacol", b =>
                {
                    b.HasOne("Spectacole_Teatru_Project.Models.Spectacol", null)
                        .WithMany()
                        .HasForeignKey("CategoriiSpectacolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spectacole_Teatru_Project.Models.Categorie", null)
                        .WithMany()
                        .HasForeignKey("CategoriiSpectacolID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spectacole_Teatru_Project.Models.Spectacol", b =>
                {
                    b.HasOne("Spectacole_Teatru_Project.Models.Regizor", "Regizor")
                        .WithMany("Spectacole")
                        .HasForeignKey("RegizorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regizor");
                });

            modelBuilder.Entity("Spectacole_Teatru_Project.Models.Regizor", b =>
                {
                    b.Navigation("Spectacole");
                });
#pragma warning restore 612, 618
        }
    }
}
